name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#---------PACKAGES--------------#

dependencies:
  flutter:
    sdk: flutter

#UTILITY PACKAGES


#ICONS
  iconsax: ^0.0.8 # we will use icons from here in our project, this is not there in default
  cupertino_icons: ^1.0.6

#STATE MANAGEMENT
  get: ^4.6.6 #state management packages which we well use, not in default


#PRODUCT SPECIFIC

#---------PACKAGES END--------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true

#---------LOCAL ASSETS--------------#

  #the / at the end of assets in important since that means we include all the content
  #in that directory
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/

#---------LOCAL FONTS--------------#
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: Italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: Italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: Italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: Italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: Italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: Italic

